# Fix for AGP 8+ Several environment variables conflict
# systemProp.ANDROID_USER_HOME=/home/giuseppe/.android
# systemProp.ANDROID_PREFS_ROOT=/home/giuseppe/.android

# Enable AndroidX
android.useAndroidX=true

# Increase memory to avoid GC thrashing and Kotlin daemon crashes
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx2048m
