# Fix for AGP 8+ Several environment variables conflict
# systemProp.ANDROID_USER_HOME=/home/giuseppe/.android
# systemProp.ANDROID_PREFS_ROOT=/home/giuseppe/.android

# Enable AndroidX
android.useAndroidX=true

# Increase memory to avoid GC thrashing and Kotlin daemon crashes
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
kotlin.daemon.jvmargs=-Xmx2048m
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true

# Performance & Size Optimizations
android.enableR8.fullMode=true
android.r8.optimizedResourceShrinking=true
android.nonTransitiveRClass=true
android.enableResourceOptimizations=true

android.builtInKotlin=false
android.newDsl=false
